"""add datetime

Revision ID: b622d728ab18
Revises: a27d58f44c41
Create Date: 2024-06-23 15:31:40.709336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b622d728ab18'
down_revision: Union[str, None] = 'a27d58f44c41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('created_time', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('updated', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated')
    op.drop_column('projects', 'created_time')
    # ### end Alembic commands ###
