"""change db projects

Revision ID: 0a5da0ee96c3
Revises: b257cdca44d2
Create Date: 2024-06-16 13:21:19.428860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a5da0ee96c3'
down_revision: Union[str, None] = 'b257cdca44d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admins', 'telegram_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('contact_methods', 'method',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('project_reviews', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('project_reviews', 'reviewer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('project_reviews', 'rating',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('project_reviews', 'comment',
               existing_type=sa.TEXT(),
               nullable=False)
    op.add_column('projects', sa.Column('salary', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('projects', 'title',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('projects', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('projects', 'start_time',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('projects', 'end_time',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('projects', 'participants_needed',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('projects', 'repository_url',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('projects', 'creator_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('projects', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('projects', 'hourly_rate')
    op.alter_column('specializations', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('user_projects', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_projects', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_reviews', 'reviewer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_reviews', 'reviewed_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_reviews', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_reviews', 'rating',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_reviews', 'comment',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('users', 'contacts',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('users', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('users', 'telegram_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('users', 'registered',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'registered',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('users', 'telegram_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'contacts',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('user_reviews', 'comment',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('user_reviews', 'rating',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_reviews', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_reviews', 'reviewed_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_reviews', 'reviewer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_projects', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_projects', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('specializations', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.add_column('projects', sa.Column('hourly_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.alter_column('projects', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('projects', 'creator_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('projects', 'repository_url',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('projects', 'participants_needed',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('projects', 'end_time',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('projects', 'start_time',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('projects', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('projects', 'title',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('projects', 'salary')
    op.alter_column('project_reviews', 'comment',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('project_reviews', 'rating',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('project_reviews', 'reviewer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('project_reviews', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('contact_methods', 'method',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('admins', 'telegram_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
