"""...

Revision ID: a77749e70572
Revises: 92786ea3ac19
Create Date: 2024-06-18 21:52:11.945630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a77749e70572'
down_revision: Union[str, None] = '92786ea3ac19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_qualification_employee', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('project_qualification_employee', 'qualification_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('project_qualification_employee', 'salary_types_id',
               existing_type=sa.INTEGER(),
               nullable=False,
                server_default='0')
    op.alter_column('project_qualification_employee', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_qualification_employee', 'amount',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('project_qualification_employee', 'salary_types_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('project_qualification_employee', 'qualification_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('project_qualification_employee', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
